import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="de"
      className="h-full antialiased"
    >
      <body className={`${inter.className} min-h-screen flex flex-col`}>
        <header className="bg-lime-100 dark:bg-gray-800 p-4">
          <h1 className="text-center">Header</h1>
        </header>
        {children}
        <footer className="bg-lime-100 dark:bg-gray-800 p-4">
          <h1 className="text-center">Footer</h1>
        </footer>
      </body>
    </html>
  );
}
